version: "3.9"

services:
  bank-discovery-service:
    build: ./discovery-service
    container_name: bank-discovery-service
    ports:
      - "8761:8761"
    expose:
      - "8761"
    environment:
      - SERVER_PORT=8761
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      retries: 10
      start_period: 10s

  bank-config-service:
    build: ./config-service
    container_name: bank-config-service
    ports:
      - "9999:9999"
    expose:
      - "9999"
    environment:
      - DISCOVERY_SERVICE_URL=http://bank-discovery-service:8761/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/actutor/health"]
      interval: 10s
      retries: 10
      start_period: 10s
    depends_on:
      bank-discovery-service:
        condition: service_healthy

  bank-customer-service:
    build: ./customer-service
    container_name: bank-customer-service
    ports:
      - "8081:8081"
    expose:
      - "8081"
    environment:
      - DISCOVERY_SERVICE_URL=http://bank-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://bank-config-service:9999
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 10s
      retries: 10
      start_period: 10s
    depends_on:
      bank-config-service:
        condition: service_healthy

  bank-account-service:
    build: ./account-service
    container_name: bank-account-service
    ports:
      - "8082:8082"
    expose:
      - "8082"
    environment:
      - DISCOVERY_SERVICE_URL=http://bank-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://bank-config-service:9999
    depends_on:
      bank-customer-service:
        condition: service_healthy

  bank-gateway-service:
    build: ./gateway-service
    container_name: bank-gateway-service
    ports:
      - "8888:8888"
    expose:
      - "8888"
    environment:
      - SERVER_PORT=8888
      - CONFIG_SERVICE_URL=http://bank-config-service:9999
      - DISCOVERY_SERVICE_URL=http://bank-discovery-service:8761/eureka
    depends_on:
      bank-discovery-service:
        condition: service_healthy
      bank-config-service:
        condition: service_healthy
  front-end-angular:
    build: ./angular-front-end
    container_name: front-end-angular
    ports:
      - '80:80'
    expose:
      - '80'

